name: earth-analytics-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  
  # Core scientific python
  - numpy
  - pyqt
  - tqdm
  - kiwisolver
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn

  # Spatial packages
  - pysal
  - pyproj>=3.0
  - rasterstats
  - geopy
  - cartopy
  - descartes
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy
  - xarray
  - rioxarray>=0.3.0
  - xarray-spatial
  - scipy
  - netcdf4
  - nc-time-axis
  - regionmask

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - papermill
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse
  
  # QA
  - flake8
  - black
  - autopep8
  - pydocstyle
  - nbqa
  
  # Autograding
  - nbgrader
