name: earth-analytics-python
channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - python=3.10
  - pip
  
  # Core scientific python
  - numpy
  - pyqt
  - tqdm
  - kiwisolver
  
  # ML
  - scikit-learn
  # - pytorch
  # - torchvision
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn
  - hvplot

  # Spatial packages
  - pysal
  - pyproj>=3.0
  - rasterstats
  - geopy
  - cartopy
  - descartes
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy
  - xarray
  - rioxarray>=0.3.0
  # - xarray-spatial
  - h5py
  - scipy
  - netcdf4
  - nc-time-axis
  - regionmask

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - papermill
  - jupyterlab
  - notebook
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - nbresuse

  # Textbook Format
  - jupyter-book
  - sphinx-exercise
  - ghp-import
  
  # QA
  - flake8
  - flake8-import-order
  - black
  - autopep8
  - pydocstyle
  - nbqa
  
  # Autograding
  - nbgrader
